### ISSUE TITLE
btw this is hella outdated

### ISSUE THREAD

**Issue by THEGOLDENPRO** [mov-cli/example-plugin#1]
as the title says but I'm too lazy to fix this rn

**Comment by ananasmoe** [comment]
done

**Comment by THEGOLDENPRO** [comment]
I think you forgot to pass options to the super init function and also I think it would be nice to leave an author in pyproject.toml to serve as an example to people new to the pyproject.toml packaging standard.

I need to start adding git workflow tests for extensions as a simple test would have caught errors like such. I'll look into this some time.
